language: python
python:
    - 3.4
    - 3.5
    
before_install:
    - pip install vk
    - pip install redis
    - pip install pytest pytest-cov
    - pip install coveralls
    
services:
    - redis-server
    
script:
    - test.py
    - coverage run --source=geography-game-vk-bot test.py
    
after_success:
  coveralls
