language: python
python:
    - 3.4
    - 3.5
    
before_install:
    - pip install vk
    - pip install redis
    - pip install python-coveralls
    - pip install coveralls
    - pip install nose
    
    
services:
    - redis-server
    
script:
   # - python setup.py install
   #- coverage run --source=geography-game-vk-bot setup.py test
    - nosetests --with-coverage
    
after_success:
  coveralls
