build: false

environment:
  matrix:
    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.5"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "32"


init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/Scripts/pip.exe install nose"
  - "%PYTHON%/Scripts/pip.exe install coverage"
  install:
    - cmd: >-
      nuget install redis-64 -excludeversion
      redis-64\tools\redis-server.exe --service-install
      redis-64\tools\redis-server.exe --service-start
      
  before_build:
    - cmd: nuget restore
    
  build:
    project: StackExchange.Redis.Extensions.sln
    verbosity: minimal

test_script:
  - "%PYTHON%/Scripts/nosetests"
